--DML
--VISTAS
INSERT INTO PUBLIC.VISTAS(DESCRIPCION) VALUES ('PRODUCTO');--1
INSERT INTO PUBLIC.VISTAS(DESCRIPCION) VALUES ('TAMANHOS');--2
INSERT INTO PUBLIC.VISTAS(DESCRIPCION) VALUES ('IMAGENES');--3
INSERT INTO PUBLIC.VISTAS(DESCRIPCION) VALUES ('MARCAS');--4
INSERT INTO PUBLIC.VISTAS(DESCRIPCION) VALUES ('COLORES');--5
INSERT INTO PUBLIC.VISTAS(DESCRIPCION) VALUES ('COMPRAS');--6
INSERT INTO PUBLIC.VISTAS(DESCRIPCION) VALUES ('GRUPOS');--7
INSERT INTO PUBLIC.VISTAS(DESCRIPCION) VALUES ('ROLES');--8
INSERT INTO PUBLIC.VISTAS(DESCRIPCION) VALUES ('SECCIONES');--9
INSERT INTO PUBLIC.VISTAS(DESCRIPCION) VALUES ('VENTAS');--10
INSERT INTO PUBLIC.VISTAS(DESCRIPCION) VALUES ('INVENTARIO');--11
INSERT INTO PUBLIC.VISTAS(DESCRIPCION) VALUES ('PAGOS');--12
INSERT INTO PUBLIC.VISTAS(DESCRIPCION) VALUES ('CLIENTES');--13

--PERMISOS
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('VER_PRODUCTO', 'PERMITE VISUALIZAR PRODUCTOS', 1);--1
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('AGREGAR_PRODUCTO', 'PERMITE AGREGAR PRODUCTOS', 1);--2
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('MODIFICAR_PRODUCTO', 'PERMITE MODIFICAR PRODUCTOS', 1);--3
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('ELIMINAR_PRODUCTO', 'PERMITE ELIMINAR PRODUCTOS', 1);--4
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('VER_TAMAÑOS', 'PERMITE VISUALIZAR TAMAÑOS', 2);--5
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('AGREGAR_TAMAÑO', 'PERMITE AGREGAR TAMAÑOS', 2);--6
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('MODIFICAR_TAMAÑO', 'PERMITE MODIFICAR TAMAÑOS', 2);--7
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('ELIMINAR_TAMAÑO', 'PERMITE ELIMINAR TAMAÑOS', 2);--8
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('VER_IMAGENES', 'PERMITE VER IMAGENES', 3);--9
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('AGREGAR_IMAGENES', 'PERMITE AGREGAR IMAGENES', 3);--10
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('MODIFICAR_IMAGENES', 'PERMITE MODIFICAR IMAGENES', 3);--11
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('VER_MARCAS', 'PERMITE VISUALIZAR MARCAS', 4);--12
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('AGREGAR_MARCAS', 'PERMITE AGREGAR MARCAS', 4);--13
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('MODIFICAR_MARCAS', 'PERMITE MODIFICAR MARCAS', 4);--14
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('ELIMINAR_MARCAS', 'PERMITE ELIMINAR MARCAS', 4);--15
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('VER_COLORES', 'PERMITE VER COLORES', 5);--16
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('AGREGAR_COLORES', 'PERMITE AGREGAR COLORES', 5);--17
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('MODIFICAR_COLORES', 'PERMITE MODIFICAR COLORES', 5);--18
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('ELIMINAR_COLORES', 'PERMITE ELIMINAR COLORES', 5);--19
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('VER_COMPRAS', 'PERMITE VER COMPRAS', 6);--20
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('AGREGAR_COMPRAS', 'PERMITE AGREGAR COMPRAS', 6);--21
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('VER_GRUPOS', 'PERMITE VER GRUPOS', 7);--22
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('AGREGAR_GRUPOS', 'PERMITE AGREGAR GRUPOS', 7);--23
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('MODIFICAR_GRUPOS', 'PERMITE MODIFICAR GRUPOS', 7);--24
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('ELIMINAR_GRUPOS', 'PERMITE ELIMINAR GRUPOS', 7);--25
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('VER_ROLES', 'PERMITE VER ROLES', 8);--26
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('ASIGNAR_ROLES', 'PERMITE ASIGNAR ROLES', 8);--27
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('MODIFICAR_ROLES', 'PERMITE MODIFICAR ROLES', 8);--28
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('ELIMINAR_ROLES', 'PERMITE ELIMINAR ROLES', 8);--29
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('VER_SECCIONES', 'PERMITE VER SECCIONES', 9);--30
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('AGREGAR_SECCIONES', 'PERMITE AGREGAR SECCIONES', 9);--31
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('MODIFICAR_SECCIONES', 'PERMITE MODIFICAR SECCIONES', 9);--32
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('ELIMINAR_SECCIONES', 'PERMITE ELIMINAR SECCIONES', 9);--33
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('VER_VENTAS', 'PERMITE VER VENTAS', 10);--34
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('AGREGAR_VENTAS', 'PERMITE AGREGAR VENTAS', 10);--35
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('ACCEDER_INVENTARIO', 'PERMITE ACCEDER A INVENTARIO', 11);--36
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('REGISTRAR_POR_INVENTARIO', 'PERMITE REGISTRAR POR INVENTARIO', 11);--37
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('REGISTRAR_PAGOS', 'PERMITE REGISTRAR PAGOS', 12);--38
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('VER_PAGOS', 'PERMITE VER PAGOS', 12);--39
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('VER_CLIENTES', 'PERMITE VER CLIENTES', 13);--40
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('REGISTRAR_CLIENTE', 'PERMITE REGISTRAR CLIENTE', 13);--41
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('MODIFICAR_CLIENTE', 'PERMITE MODIFICAR CLIENTE', 13);--42
INSERT INTO PUBLIC.PERMISOS(NOMBRE, DESCRIPCION, VISTAS_COD_VISTA) VALUES ('INHABILITAR_CLIENTE', 'PERMITE INHABILITAR CLIENTE', 13);--43

--ROLES
INSERT INTO PUBLIC.ROLES(DESCRIPCION) VALUES ('BASICO');--1
INSERT INTO PUBLIC.ROLES(DESCRIPCION) VALUES ('ADMINISTRADOR');--2
INSERT INTO PUBLIC.ROLES(DESCRIPCION) VALUES ('MOVIL');--3

--PERMISOS ROLES
--REGLA DE ROLES PERMISOS, POR DEFECTO AL MOMENTO DE REGISTRARSE VA A SER BASICO, EL ADMINISTRADOR DEBE ASIGNAR
--PARA MOVIL LAS DEMAS FUNCIONALIDADES.
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (1, 1);--PARA BASICO
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (9, 1);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (30, 1);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (42, 1);

INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (20, 3);--PARA MOVIL
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (21, 3);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (34, 3);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (35, 3);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (38, 3);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (39, 3);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (40, 3);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (41, 3);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (42, 3);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (43, 3);

INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (1, 2);--PARA ADMINISTRADOR
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (2, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (3, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (4, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (5, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (6, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (7, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (8, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (9, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (10, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (11, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (12, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (13, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (14, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (15, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (16, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (17, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (18, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (19, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (20, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (21, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (22, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (23, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (24, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (25, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (26, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (27, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (28, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (29, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (30, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (31, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (32, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (33, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (34, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (35, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (36, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (37, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (38, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (39, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (40, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (41, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (42, 2);
INSERT INTO PUBLIC.PERMISOS_ROLES(COD_PERMISO, COD_ROL) VALUES (43, 2);

